"""updated the content able

Revision ID: 79026945d0db
Revises: ed349ebc2ff0
Create Date: 2026-05-13 15:41:50.153065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79026945d0db'
down_revision: Union[str, Sequence[str], None] = 'ed349ebc2ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('content_nft_id_fkey'), 'content', type_='foreignkey')
    op.drop_column('content', 'nft_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('nft_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('content_nft_id_fkey'), 'content', 'nft', ['nft_id'], ['id'])
    # ### end Alembic commands ###
