"""Prod databases init

Revision ID: ed349ebc2ff0
Revises: 
Create Date: 2026-05-13 15:27:30.831809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed349ebc2ff0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_ticket_event_id'), 'ticket', ['event_id'], unique=False)
    op.drop_column('content', 'thumbnail_status')
    op.drop_column('content', 'thumbnail_url')
    op.drop_column('nft', 'tx_signature')
    op.add_column('transaction', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=False))
    op.drop_constraint(op.f('transaction_buyer_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_seller_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'tx_hash')
    op.drop_column('transaction', 'seller_id')
    op.drop_column('transaction', 'buyer_id')
    op.alter_column('user', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'encrypted_private_key')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('encrypted_private_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('user', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('transaction', sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('tx_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('transaction_seller_id_fkey'), 'transaction', 'user', ['seller_id'], ['id'])
    op.create_foreign_key(op.f('transaction_buyer_id_fkey'), 'transaction', 'user', ['buyer_id'], ['id'])
    op.drop_column('transaction', 'status')
    op.add_column('nft', sa.Column('tx_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('thumbnail_status', postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='thumbnailstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ticket_event_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
